import './globals.css';
import '@/fontawesome';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';
import ScrollToTopButton from '../components/common/ScrollToTopButton';

export const metadata = {
  title: 'Jean Mauvoisin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="bg-black text-white">
        <Header>
          <Header />
        </Header>
        <main>
          <ScrollToTopButton />
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
