
import "./globals.css";
import "@/fontawesome";
import Header from "@/components/common/Header";

export const metadata = {
  title: "Jean Mauvoisin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="bg-black text-white">
        <Header />
          {children}
      </body>
    </html>
  );
}
