import './globals.css';
import '@/fontawesome';
import Header from '@/components/common/header';
import Footer from '@/components/common/footer';

export const metadata = {
  title: 'Jean Mauvoisin',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="bg-black text-white">
        <Header>
          <Header />
        </Header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
